ALTER TYPE "UserStatus" ADD VALUE IF NOT EXISTS 'DISABLED';

ALTER TABLE "users"
  ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 0;
